<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Inquiry;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class InquirySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run(): void
    {
        // Clear existing records to avoid duplicate unique inquiry constraint violations
        DB::table('inquiries')->truncate();

        $inquiries = [
            [
                'inquiry' => 'I am interested in booking a tour package to Bali for my family. Could you provide details about 5-day packages?',
                'pax_counts' => 4,
                'traveling_date' => '2025-07-15',
                'agent' => 'Anna Thompson',
                'from_email' => 'anna.thompson@example.com',
                'status' => 'Open',
                'person_in_charge' => 'John Smith',
                'inquiry_type' => 'Tour Package',
                'inquiry_received' => '2025-05-10 09:15:22',
                'email_subject' => 'Inquiry about Bali Tour Packages',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Looking for honeymoon packages to Maldives in September. Budget around $5000 for 7 days.',
                'pax_counts' => 2,
                'traveling_date' => '2025-09-10',
                'agent' => 'David Lee',
                'from_email' => 'david.lee@example.com',
                'status' => 'Pending',
                'person_in_charge' => 'Sarah Johnson',
                'inquiry_type' => 'Honeymoon Package',
                'inquiry_received' => '2025-05-11 14:22:30',
                'email_subject' => 'Honeymoon Package Inquiry',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Our company wants to organize a retreat for 25 employees. Looking for venues with conference facilities and team building activities.',
                'pax_counts' => 25,
                'traveling_date' => '2025-08-20',
                'agent' => 'Michael Chen',
                'from_email' => 'michael.chen@corporate.com',
                'status' => 'In Progress',
                'person_in_charge' => 'Emily Davis',
                'inquiry_type' => 'Corporate Retreat',
                'inquiry_received' => '2025-05-12 10:45:12',
                'email_subject' => 'Corporate Retreat Inquiry',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'I need information about visa requirements for traveling to Europe from Indonesia for a family of 3.',
                'pax_counts' => 3,
                'traveling_date' => '2025-06-25',
                'agent' => 'Siti Rahman',
                'from_email' => 'siti.rahman@example.com',
                'status' => 'Closed',
                'person_in_charge' => 'Robert Wilson',
                'inquiry_type' => 'Visa Information',
                'inquiry_received' => '2025-05-13 16:30:45',
                'email_subject' => 'Visa Requirements Inquiry',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Looking for adventure tour packages in New Zealand. Interested in bungee jumping, hiking, and other extreme sports.',
                'pax_counts' => 1,
                'traveling_date' => '2025-10-05',
                'agent' => 'James Wilson',
                'from_email' => 'james.wilson@example.com',
                'status' => 'Open',
                'person_in_charge' => 'Lisa Brown',
                'inquiry_type' => 'Adventure Tour',
                'inquiry_received' => '2025-05-14 08:15:33',
                'email_subject' => 'Adventure Tour in New Zealand',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Need to book a cruise package for a family reunion. We are 15 people including 5 seniors and 3 children.',
                'pax_counts' => 15,
                'traveling_date' => '2025-12-15',
                'agent' => 'Maria Garcia',
                'from_email' => 'maria.garcia@example.com',
                'status' => 'Pending',
                'person_in_charge' => 'John Smith',
                'inquiry_type' => 'Cruise Package',
                'inquiry_received' => '2025-05-15 11:20:18',
                'email_subject' => 'Family Reunion Cruise Package',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Planning a backpacking trip across Southeast Asia for 2 months. Need advice on itinerary and budget accommodations.',
                'pax_counts' => 2,
                'traveling_date' => '2025-07-01',
                'agent' => 'Ryan Thompson',
                'from_email' => 'ryan.thompson@example.com',
                'status' => 'In Progress',
                'person_in_charge' => 'Sarah Johnson',
                'inquiry_type' => 'Backpacking Trip',
                'inquiry_received' => '2025-05-16 09:45:22',
                'email_subject' => 'Southeast Asia Backpacking Trip',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Inquiring about luxury safari packages in Kenya and Tanzania for 5 people. Interested in premium accommodations.',
                'pax_counts' => 5,
                'traveling_date' => '2025-08-10',
                'agent' => 'Emma Roberts',
                'from_email' => 'emma.roberts@example.com',
                'status' => 'Open',
                'person_in_charge' => 'Emily Davis',
                'inquiry_type' => 'Safari Package',
                'inquiry_received' => '2025-05-17 14:10:30',
                'email_subject' => 'Luxury Safari Package Inquiry',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Need to book a business trip to Singapore for 3 executives. Require business class flights and 5-star hotel.',
                'pax_counts' => 3,
                'traveling_date' => '2025-06-10',
                'agent' => 'William Chen',
                'from_email' => 'william.chen@corporate.com',
                'status' => 'Pending',
                'person_in_charge' => 'Robert Wilson',
                'inquiry_type' => 'Business Travel',
                'inquiry_received' => '2025-05-18 16:25:40',
                'email_subject' => 'Business Trip to Singapore',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Looking for a budget-friendly family trip to Thailand during school holidays. Family of 6 with 4 children under 12.',
                'pax_counts' => 6,
                'traveling_date' => '2025-07-20',
                'agent' => 'Nurul Hidayah',
                'from_email' => 'nurul.hidayah@example.com',
                'status' => 'Open',
                'person_in_charge' => 'Lisa Brown',
                'inquiry_type' => 'Family Vacation',
                'inquiry_received' => '2025-05-19 10:15:50',
                'email_subject' => 'Family Trip to Thailand',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Interested in a cultural tour of Japan during cherry blossom season. Group of 4 adults.',
                'pax_counts' => 4,
                'traveling_date' => '2026-04-05',
                'agent' => 'Daniel Kim',
                'from_email' => 'daniel.kim@example.com',
                'status' => 'Open',
                'person_in_charge' => 'John Smith',
                'inquiry_type' => 'Cultural Tour',
                'inquiry_received' => '2025-05-20 09:30:15',
                'email_subject' => 'Japan Cherry Blossom Tour',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Need to arrange a customized tour of Australia for a retired couple. Interested in natural wonders and wildlife.',
                'pax_counts' => 2,
                'traveling_date' => '2025-09-15',
                'agent' => 'Jennifer White',
                'from_email' => 'jennifer.white@example.com',
                'status' => 'In Progress',
                'person_in_charge' => 'Sarah Johnson',
                'inquiry_type' => 'Customized Tour',
                'inquiry_received' => '2025-05-21 13:45:25',
                'email_subject' => 'Australia Customized Tour',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Requesting information about historical tours in Europe covering multiple countries. Group of 8 history enthusiasts.',
                'pax_counts' => 8,
                'traveling_date' => '2025-10-10',
                'agent' => 'Thomas Brown',
                'from_email' => 'thomas.brown@example.com',
                'status' => 'Pending',
                'person_in_charge' => 'Emily Davis',
                'inquiry_type' => 'Historical Tour',
                'inquiry_received' => '2025-05-22 11:20:35',
                'email_subject' => 'European Historical Tour',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Planning a graduation trip to South Korea for 6 university graduates. Looking for modern city experiences and K-pop related activities.',
                'pax_counts' => 6,
                'traveling_date' => '2025-08-01',
                'agent' => 'Sophia Lee',
                'from_email' => 'sophia.lee@example.com',
                'status' => 'Open',
                'person_in_charge' => 'Robert Wilson',
                'inquiry_type' => 'Graduation Trip',
                'inquiry_received' => '2025-05-23 15:10:20',
                'email_subject' => 'South Korea Graduation Trip',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'inquiry' => 'Need a winter holiday package in Switzerland for a family of 5. Interested in skiing and snow activities.',
                'pax_counts' => 5,
                'traveling_date' => '2025-12-20',
                'agent' => 'Mohammad Rahman',
                'from_email' => 'mohammad.rahman@example.com',
                'status' => 'Pending',
                'person_in_charge' => 'Lisa Brown',
                'inquiry_type' => 'Winter Holiday',
                'inquiry_received' => '2025-05-24 08:55:45',
                'email_subject' => 'Switzerland Winter Holiday Package',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        foreach ($inquiries as $inquiryData) {
            Inquiry::create($inquiryData);
        }
    }
}